title: "Effects of different penetrations of BEV in suburban areas on the grid stability"
author: André Ulrich
logo: img/SNEE-logo.jpg

execute:
    execute_notebooks: "off"

html:
    extra_navbar: |
        <div>
            <b>SNEE PG14 in SoSe2021</b><br>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
        </div>
        
    extra_footer: |
        <p>
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/legalcode">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
        <p>
        
sphinx:
    config:
        html_show_copyright: false